-- Add migration script here
CREATE TABLE users (
    guild_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    cookie_sent INT UNSIGNED NOT NULL DEFAULT 0,
    cookie_received INT UNSIGNED NOT NULL DEFAULT 0,
    slap_sent INT UNSIGNED NOT NULL DEFAULT 0,
    slap_received INT UNSIGNED NOT NULL DEFAULT 0,
    cake_sent INT UNSIGNED NOT NULL DEFAULT 0,
    cake_received INT UNSIGNED NOT NULL DEFAULT 0,
    tea_sent INT UNSIGNED NOT NULL DEFAULT 0,
    tea_received INT UNSIGNED NOT NULL DEFAULT 0,
    bomb_sent INT UNSIGNED NOT NULL DEFAULT 0,
    bomb_defused INT UNSIGNED NOT NULL DEFAULT 0,
    bomb_failed INT UNSIGNED NOT NULL DEFAULT 0
)