-- Add migration script here
ALTER TABLE `users`
  ADD COLUMN `rps_win` INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rps_loss` INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `rps_tie` INT UNSIGNED NOT NULL DEFAULT 0